//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.WorkersBenefits.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public string product_uid { get; set; }
        public int category_id { get; set; }
        public string image { get; set; }
        public string title { get; set; }
        public Nullable<int> precedence { get; set; }
        public string description { get; set; }
        public string popup { get; set; }
        public Nullable<decimal> initial_price { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> shipping { get; set; }
        public decimal final_price { get; set; }
        public Nullable<int> globalPrecedence { get; set; }
    
        public virtual category category { get; set; }
        public virtual products_in_orders products_in_orders { get; set; }
    }
}
