//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.WorkersBenefits.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public int category_id { get; set; }
        public int product_type_id { get; set; }
        public string image { get; set; }
        public string title { get; set; }
        public decimal price { get; set; }
        public string restrictions { get; set; }
        public string description { get; set; }
        public string popup { get; set; }
    
        public virtual category category { get; set; }
        public virtual product_types product_types { get; set; }
    }
}
