//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.WorkersBenefits.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voucher()
        {
            this.voucher_grants = new HashSet<voucher_grants>();
            this.voucher_requests = new HashSet<voucher_requests>();
        }
    
        public int voucher_id { get; set; }
        public string image { get; set; }
        public System.DateTime valid_start_date { get; set; }
        public Nullable<System.DateTime> valid_end_date { get; set; }
        public string description { get; set; }
        public bool active { get; set; }
        public System.DateTime last_updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voucher_grants> voucher_grants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voucher_requests> voucher_requests { get; set; }
    }
}
