//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.WorkersBenefits.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher_requests
    {
        public int voucher_request_id { get; set; }
        public int worker_id { get; set; }
        public int voucher_id { get; set; }
        public System.DateTime request_date { get; set; }
    
        public virtual voucher voucher { get; set; }
        public virtual worker worker { get; set; }
    }
}
