//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.WorkersBenefits.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker_purchase_history
    {
        public int purchase_id { get; set; }
        public int product_id { get; set; }
        public decimal discount { get; set; }
        public decimal final_price { get; set; }
        public System.DateTime purchase_date { get; set; }
    }
}
