//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.WorkersBenefits.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkersBenefitsDB2 : DbContext
    {
        public WorkersBenefitsDB2()
            : base("name=WorkersBenefitsDB2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_person_settings> admin_person_settings { get; set; }
        public virtual DbSet<admin_persons> admin_persons { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<company_person_settings> company_person_settings { get; set; }
        public virtual DbSet<company_persons> company_persons { get; set; }
        public virtual DbSet<global_settings> global_settings { get; set; }
        public virtual DbSet<order_payments> order_payments { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<products_in_orders> products_in_orders { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<userclaim> userclaims { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<voucher_grants> voucher_grants { get; set; }
        public virtual DbSet<voucher_requests> voucher_requests { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
        public virtual DbSet<worker_settings> worker_settings { get; set; }
        public virtual DbSet<worker> workers { get; set; }
    }
}
