//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.WorkersBenefits.BL.GoldmanSMSServce {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smsapi.co.il/", ConfigurationName="GoldmanSMSServce.SendSMSSoap")]
    public interface SendSMSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsapi.co.il/SUBMITSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SUBMITSMS(string XMLString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsapi.co.il/SUBMITSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SUBMITSMSAsync(string XMLString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsapi.co.il/COMMANDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string COMMANDS(string XMLString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsapi.co.il/COMMANDS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> COMMANDSAsync(string XMLString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSMSSoapChannel : EMX.WorkersBenefits.BL.GoldmanSMSServce.SendSMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSMSSoapClient : System.ServiceModel.ClientBase<EMX.WorkersBenefits.BL.GoldmanSMSServce.SendSMSSoap>, EMX.WorkersBenefits.BL.GoldmanSMSServce.SendSMSSoap {
        
        public SendSMSSoapClient() {
        }
        
        public SendSMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SUBMITSMS(string XMLString) {
            return base.Channel.SUBMITSMS(XMLString);
        }
        
        public System.Threading.Tasks.Task<string> SUBMITSMSAsync(string XMLString) {
            return base.Channel.SUBMITSMSAsync(XMLString);
        }
        
        public string COMMANDS(string XMLString) {
            return base.Channel.COMMANDS(XMLString);
        }
        
        public System.Threading.Tasks.Task<string> COMMANDSAsync(string XMLString) {
            return base.Channel.COMMANDSAsync(XMLString);
        }
    }
}
